
// module: res.h

#define ABOUTBOX        100

/* Menu IDs */

#define IDM_OPEN        1002
#define IDM_EXIT        1003
#define IDM_ABOUT       1004
#define IDM_DIBSCREEN   1005
#define IDM_NOUGLY      1006
#define IDM_STEALCOL    1009
#define IDM_PRINT       1010
#define IDM_COPY        1012
#define IDM_MEMORYDIB   1014
#define IDM_SAVE        1015
#define IDM_TRANSPARENT 1016

#define IDM_PASTEDIB    1020
#define IDM_PASTEDDB    1021
#define IDM_PASTEPAL    1022

#define IDM_UPDATECOL   1023
#define IDM_ANIMATE0    1024
#define IDM_ANIMATE5    1025
#define IDM_ANIMATE20   1026
#define IDM_ANIMATE50   1027
#define IDM_ANIMATE100  1028
#define IDM_ANIMATE200  1029
#define IDM_ANIMATE201  1030

/*String IDs*/
#define IDS_MEMLOW          650
#define IDS_NOMEM           651
#define IDS_OPENDIBPROMPT   652
#define IDS_SAVEDIBPROMPT   653
#define IDS_CANTSAVEFILE    654
#define IDS_CANTOPENFILE    655
#define IDS_BADDIBFILE      656
#define IDS_CREATEPALFAIL   657
#define IDS_CANTLOADRLE     658
#define IDS_CANTCREATEBMP   659
#define IDS_CANTDRAWSCANS   660
#define IDS_CANTDRAWMAP     661
#define IDS_SAVESTR         662
#define IDS_OPENSTR         663

// eof - res.h
